import { Product, Review, InstagramPost } from './types';

export const HERO_IMAGE = '/src/assets/images/aura_luxe_hero_1783852073342.jpg';

export const COLLECTIONS = [
  {
    id: 'celestial',
    name: 'The Celestial Line',
    tagline: 'Inspired by the celestial bodies and cosmic alignments.',
    description: 'A harmonious blend of emerald-cut diamonds and 18K yellow gold, echoing the infinite brilliance of the stars.',
    image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&q=80&w=800',
    itemCount: 12,
  },
  {
    id: 'solitaire',
    name: 'Solitaire Luminary',
    tagline: 'Singular, breathtaking brilliance in pure platinum.',
    description: 'Each piece features an exceptionally graded, ethically sourced single diamond designed to capture and refract maximum light.',
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&q=80&w=800',
    itemCount: 8,
  },
  {
    id: 'gilded-whispers',
    name: 'Gilded Whispers',
    tagline: 'Intricate, delicate textures crafted by master artisans.',
    description: 'Fine filigree and hand-hammered 24K rose gold creations that speak of quiet luxury and elegant personal stories.',
    image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&q=80&w=800',
    itemCount: 15,
  },
];

export const PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Sovereign Emerald Cut Ring',
    category: 'Rings',
    price: 14500,
    rating: 4.9,
    reviewsCount: 38,
    image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&q=80&w=800',
    isBestSeller: true,
    isNewArrival: false,
    description: 'An exceptional 3.5-carat emerald-cut VVS1 diamond, flanked by tapered baguettes, set in a meticulously polished platinum band. Exemplifies high-society refinement.',
    material: 'Platinum',
    gemstone: 'Diamond (3.5ct)',
    sku: 'AL-R-092-PT',
    stockStatus: 'In Stock',
    dateAdded: '2025-12-01'
  },
  {
    id: 'p2',
    name: 'Aurelia 18K Gold Choker',
    category: 'Necklaces',
    price: 8900,
    rating: 4.8,
    reviewsCount: 42,
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&q=80&w=800',
    isBestSeller: true,
    isNewArrival: false,
    description: 'Hand-linked liquid 18K yellow gold choker that drapes gracefully over the collarbone. Highly reflective polished surface with an invisible safety clasp.',
    material: '18K Yellow Gold',
    sku: 'AL-N-104-YG',
    originalPrice: 10500,
    discountBadge: '15% OFF',
    stockStatus: 'Low Stock',
    dateAdded: '2025-11-15'
  },
  {
    id: 'p3',
    name: 'Baroque Pearl Drop Earrings',
    category: 'Earrings',
    price: 3200,
    rating: 4.7,
    reviewsCount: 29,
    image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&q=80&w=800',
    isBestSeller: true,
    isNewArrival: false,
    description: 'Stunning asymmetric South Sea baroque pearls suspended from diamond-encrusted 18K white gold Huggies. Every pearl is completely unique, selected for its exquisite luster.',
    material: '18K White Gold',
    gemstone: 'South Sea Pearl & Diamonds',
    sku: 'AL-E-211-WG',
    stockStatus: 'In Stock',
    dateAdded: '2025-10-10'
  },
  {
    id: 'p4',
    name: 'Starlight Diamond Tennis Bracelet',
    category: 'Bracelets',
    price: 18200,
    rating: 5.0,
    reviewsCount: 16,
    image: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&q=80&w=800',
    isBestSeller: true,
    isNewArrival: true,
    description: 'A continuous line of 58 brilliant round-cut diamonds, totaling 8.5 carats, set in a seamless fluid four-prong 18K white gold mounting.',
    material: '18K White Gold',
    gemstone: 'Diamond (8.5ctw)',
    sku: 'AL-B-403-WG',
    originalPrice: 21000,
    discountBadge: 'Bespoke Deal',
    stockStatus: 'In Stock',
    dateAdded: '2026-01-10'
  },
  {
    id: 'p5',
    name: 'Verdant Horizon Emerald Band',
    category: 'Rings',
    price: 12400,
    rating: 4.9,
    reviewsCount: 21,
    image: 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&q=80&w=800',
    isBestSeller: false,
    isNewArrival: true,
    description: 'Alternating cushion-cut natural Colombian emeralds and brilliant round diamonds, channel-set in an architectural 18K yellow gold modern band.',
    material: '18K Yellow Gold',
    gemstone: 'Colombian Emerald & Diamond',
    sku: 'AL-R-552-YG',
    stockStatus: 'In Stock',
    dateAdded: '2026-02-15'
  },
  {
    id: 'p6',
    name: 'Celestial Diamond Set',
    category: 'Sets',
    price: 32000,
    rating: 5.0,
    reviewsCount: 14,
    image: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&q=80&w=800',
    isBestSeller: true,
    isNewArrival: true,
    description: 'A breathtaking high-jewelry suite including a brilliant-cut diamond pendant necklace and matching drop earrings. Perfectly paired for major milestones.',
    material: '18K White Gold',
    gemstone: 'Diamonds (12.4ctw)',
    sku: 'AL-S-001-WG',
    originalPrice: 38000,
    discountBadge: 'Exclusive Suite',
    stockStatus: 'Low Stock',
    dateAdded: '2026-03-01'
  },
  {
    id: 'p7',
    name: 'Royal Sapphire Solitaire Pendant',
    category: 'Necklaces',
    price: 16800,
    rating: 4.8,
    reviewsCount: 19,
    image: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&q=80&w=800',
    isBestSeller: false,
    isNewArrival: true,
    description: 'An mesmerizing 4.2-carat royal blue oval-cut Ceylon sapphire, suspended on an elegant 18K white gold micro-pave chain. Inspired by royalty and noble heritage.',
    material: '18K White Gold',
    gemstone: 'Ceylon Sapphire (4.2ct)',
    sku: 'AL-N-904-WG',
    stockStatus: 'In Stock',
    dateAdded: '2026-01-20'
  },
  {
    id: 'p8',
    name: 'Ribbon Twist Hoop Earrings',
    category: 'Earrings',
    price: 4500,
    rating: 4.6,
    reviewsCount: 31,
    image: 'https://images.unsplash.com/photo-1635767798638-3e25273a8236?auto=format&fit=crop&q=80&w=800',
    isBestSeller: false,
    isNewArrival: true,
    description: 'Modern, architectural twist-ribbon hoops in ultra-reflective 18K yellow gold, inlaid with fine rows of micro-diamonds along the interior and exterior curves.',
    material: '18K Yellow Gold',
    gemstone: 'Diamonds (0.6ctw)',
    sku: 'AL-E-772-YG',
    stockStatus: 'Out of Stock',
    dateAdded: '2026-02-10'
  },
  {
    id: 'p9',
    name: 'Luminescent Diamond Bangle',
    category: 'Bangles',
    price: 7800,
    rating: 4.8,
    reviewsCount: 15,
    image: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&q=80&w=800',
    isBestSeller: false,
    isNewArrival: false,
    description: 'An exquisite hand-carved 18K yellow gold bangle adorned with princess-cut pave-set conflict-free diamonds.',
    material: '18K Yellow Gold',
    gemstone: 'Diamond (2.1ctw)',
    sku: 'AL-B-112-YG',
    originalPrice: 9200,
    discountBadge: 'Aura Classic',
    stockStatus: 'In Stock',
    dateAdded: '2025-08-25'
  },
  {
    id: 'p10',
    name: 'Gilded Whispers Cuff Bangle',
    category: 'Bangles',
    price: 9500,
    rating: 4.9,
    reviewsCount: 22,
    image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&q=80&w=800',
    isBestSeller: true,
    isNewArrival: false,
    description: 'A sculpted bold cuff in rose gold with fine filigree patterns and miniature round diamond highlights.',
    material: '18K Rose Gold',
    gemstone: 'Diamond (1.5ctw)',
    sku: 'AL-B-334-RG',
    stockStatus: 'In Stock',
    dateAdded: '2025-09-12'
  },
  {
    id: 'p11',
    name: 'Siren Emerald Set',
    category: 'Sets',
    price: 45000,
    rating: 5.0,
    reviewsCount: 8,
    image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&q=80&w=800',
    isBestSeller: false,
    isNewArrival: true,
    description: 'A complete custom set of Colombian emerald and diamond halo ring with matching double-tiered necklace and drop earrings.',
    material: 'Platinum',
    gemstone: 'Colombian Emerald & VVS Diamonds',
    sku: 'AL-S-222-PT',
    stockStatus: 'In Stock',
    dateAdded: '2026-03-10'
  },
  {
    id: 'p12',
    name: 'Empress Diamond Chandelier Earrings',
    category: 'Earrings',
    price: 13900,
    rating: 4.9,
    reviewsCount: 17,
    image: 'https://images.unsplash.com/photo-1635767798638-3e25273a8236?auto=format&fit=crop&q=80&w=800',
    isBestSeller: true,
    isNewArrival: false,
    description: 'Cascading tiers of pear and marquise cut diamonds set in 18K white gold. Inspired by Royal Court style.',
    material: '18K White Gold',
    gemstone: 'Diamond (5.2ctw)',
    sku: 'AL-E-902-WG',
    originalPrice: 16500,
    discountBadge: 'Rare Find',
    stockStatus: 'In Stock',
    dateAdded: '2025-11-20'
  }
];

export const REVIEWS: Review[] = [
  {
    id: 'r1',
    author: 'Eleanor Vance',
    rating: 5,
    text: 'Aura Luxe represents the pinnacle of modern luxury jewelry. The Sovereign Emerald Ring exceeded all expectations. The brilliance and cut of the stone is a masterclass in artistry. Customer service was exquisite, providing a tailored white-glove delivery experience.',
    date: 'June 18, 2026',
    verified: true,
    productBought: 'Sovereign Emerald Cut Ring'
  },
  {
    id: 'r2',
    author: 'Julian Sterling',
    rating: 5,
    text: 'I commissioned custom adjustments to the Aurelia Gold Choker. The design team was highly responsive, incorporating family gemstones with infinite respect and precision. Truly timeless pieces that my children will inherit.',
    date: 'May 04, 2026',
    verified: true,
    productBought: 'Aurelia 18K Gold Choker'
  },
  {
    id: 'r3',
    author: 'Victoria Sterling-Hume',
    rating: 5,
    text: 'Each piece is an architectural monument. The South Sea Pearl Earrings have a breathtaking pinkish-blue orient luster that pairs magnificently with both casual silk and formal evening gowns. Sublime craft.',
    date: 'April 22, 2026',
    verified: true,
    productBought: 'Baroque Pearl Drop Earrings'
  }
];

export const INSTAGRAM_FEED: InstagramPost[] = [
  {
    id: 'ig1',
    image: 'https://images.unsplash.com/photo-1543294001-f7cbfe92237e?auto=format&fit=crop&q=80&w=600',
    likes: '4.8k',
    tag: '#AuraLuxeGala',
    productIds: ['p2', 'p4']
  },
  {
    id: 'ig2',
    image: 'https://images.unsplash.com/photo-1481824429379-07aa5e5b0739?auto=format&fit=crop&q=80&w=600',
    likes: '3.2k',
    tag: '#BehindTheCraft',
    productIds: ['p1']
  },
  {
    id: 'ig3',
    image: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&q=80&w=600',
    likes: '5.9k',
    tag: '#TimelessElegance',
    productIds: ['p6']
  },
  {
    id: 'ig4',
    image: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&q=80&w=600',
    likes: '6.1k',
    tag: '#AuraLuxeMuses',
    productIds: ['p3', 'p7']
  }
];
